### ISSUE TITLE
Input/Output properties

### ISSUE THREAD

**Issue by dalcacer** [richwps/modelbuilder#60]
**LiteralInputPort**
* DataType, 0..*, `DataType of this input`
* UOMs, 0..* `List of units of measure supported for this numerical input`
* LiteralValuesChoice, 1, `Identifies type of literal input and provides supporting information`
  * AllowedValues, 0..1
  * AnyValue, 0..1
  * ValuesReference, 0..1
* DefaultValues, 0...1, `Default value for this input encoded in character string.`

**LiterlOutputPort**
* DataType, 0..*, `DataType of this output.`
* UOMs, 0..* `List of units of measure supported for this numerical output`

**Comment by dziegenh** [comment]
Implementation prepared by refactoring the ProcessPort entities.
Todo: Add entities for UOMs etc.
